baseURL = 'https://suryapsp.netlify.app'
languageCode = 'en-us'
title = 'suryapsp'
theme = 'etch'
copyright = "© 2023-2024 Surya Singh"

[menu]
    [[menu.main]]
        identifier = 'about'
        name = 'About'
        url = '/about'
        weight = 10

    [[menu.main]]
        identifier = 'mail'
        name = 'mail'
        url = 'mailto:suryasingh2522@gmail.com'
        weight = 20